name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  matrix-ci:
    name: CI (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Check CLI
        working-directory: app
        run: cargo check --locked

  ci:
    name: CI
    needs: matrix-ci
    runs-on: ubuntu-latest
    steps:
      - run: true
